### ISSUE TITLE
Get information about whether the property has been purchased.

### ISSUE THREAD

**Issue by HTTDIENTE** [almamedia/kivi-wordpress#21]
I need to determine on the WordPress side whether the property has been purchased so that I can hide it from the list of all listings.
How to do this?

**Comment by kristianahonen** [comment]
If WP cron is running at least once in hour, properties that are no longer active will be deleted automatically. 
https://developer.wordpress.org/plugins/cron/
If WP cron is missed for multiple hours and properties are sold during that time, those should be deleted manually as no data will update on those properties. This can happen for example in developer environment if there is no system cron installed.

Or you can click reset (wait for items to be deleted) and then click Nouda / päivitä kaikki. That will delete all and bring back only active properties.
